### ISSUE TITLE
Muted attribute for videoEmbed

### ISSUE THREAD

**Issue by guidogambini1995** [andresclua/boostify#3]
Hi, @andresclua! I was wondering if it would be possible including a 'muted' attribute for the videoEmbed so I can decide between both options.

Thanks a lot for the Library. It looks awesome and super helpful!

**Comment by andresclua** [comment]
hey @guidogambini1995 , 

Most modern browsers, such as Chrome, Firefox, and Safari, have implemented policies that restrict the automatic playback of videos with sound without direct user interaction. This means that if you attempt to start a video automatically via JavaScript and without it being muted, the browser is likely to ignore these instructions and not play the sound, or even not play the video at all.

The best practice is to respect the browser's autoplay policies and allow the user to manually start the video if they wish. You can provide playback controls so that the user can toggle sound on or off and control playback according to their preferences.
